# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\runsummary\RunSummary_Widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RunSummaryWidget(object):
    def setupUi(self, RunSummaryWidget):
        RunSummaryWidget.setObjectName(_fromUtf8("RunSummaryWidget"))
        RunSummaryWidget.resize(740, 577)
        self.verticalLayout_2 = QtGui.QVBoxLayout(RunSummaryWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.overviewGroup = QtGui.QGroupBox(RunSummaryWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.overviewGroup.setFont(font)
        self.overviewGroup.setObjectName(_fromUtf8("overviewGroup"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.overviewGroup)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.overviewLabel = QtGui.QLabel(self.overviewGroup)
        self.overviewLabel.setWordWrap(True)
        self.overviewLabel.setObjectName(_fromUtf8("overviewLabel"))
        self.verticalLayout_4.addWidget(self.overviewLabel)
        self.verticalLayout_2.addWidget(self.overviewGroup)
        self.runStatusGroup = QtGui.QGroupBox(RunSummaryWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial 12"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.runStatusGroup.setFont(font)
        self.runStatusGroup.setObjectName(_fromUtf8("runStatusGroup"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.runStatusGroup)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.updateAllStatusButton = QtGui.QPushButton(self.runStatusGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateAllStatusButton.sizePolicy().hasHeightForWidth())
        self.updateAllStatusButton.setSizePolicy(sizePolicy)
        self.updateAllStatusButton.setObjectName(_fromUtf8("updateAllStatusButton"))
        self.horizontalLayout.addWidget(self.updateAllStatusButton)
        self.tlfAddButton = QtGui.QPushButton(self.runStatusGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tlfAddButton.sizePolicy().hasHeightForWidth())
        self.tlfAddButton.setSizePolicy(sizePolicy)
        self.tlfAddButton.setObjectName(_fromUtf8("tlfAddButton"))
        self.horizontalLayout.addWidget(self.tlfAddButton)
        self.autoUpdateButton = QtGui.QPushButton(self.runStatusGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoUpdateButton.sizePolicy().hasHeightForWidth())
        self.autoUpdateButton.setSizePolicy(sizePolicy)
        self.autoUpdateButton.setObjectName(_fromUtf8("autoUpdateButton"))
        self.horizontalLayout.addWidget(self.autoUpdateButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.showFmpRunCbox = QtGui.QCheckBox(self.runStatusGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showFmpRunCbox.sizePolicy().hasHeightForWidth())
        self.showFmpRunCbox.setSizePolicy(sizePolicy)
        self.showFmpRunCbox.setChecked(True)
        self.showFmpRunCbox.setObjectName(_fromUtf8("showFmpRunCbox"))
        self.horizontalLayout.addWidget(self.showFmpRunCbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.runStatusTable = QtGui.QTableWidget(self.runStatusGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runStatusTable.sizePolicy().hasHeightForWidth())
        self.runStatusTable.setSizePolicy(sizePolicy)
        self.runStatusTable.setObjectName(_fromUtf8("runStatusTable"))
        self.runStatusTable.setColumnCount(6)
        self.runStatusTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.runStatusTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.runStatusTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.runStatusTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.runStatusTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.runStatusTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        item.setFont(font)
        self.runStatusTable.setHorizontalHeaderItem(5, item)
        self.runStatusTable.horizontalHeader().setCascadingSectionResizes(True)
        self.runStatusTable.horizontalHeader().setDefaultSectionSize(100)
        self.runStatusTable.horizontalHeader().setMinimumSectionSize(50)
        self.runStatusTable.horizontalHeader().setStretchLastSection(True)
        self.runStatusTable.verticalHeader().setDefaultSectionSize(20)
        self.runStatusTable.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.runStatusTable)
        self.verticalLayout_2.addWidget(self.runStatusGroup)
        self.graphLayoutH = QtGui.QHBoxLayout()
        self.graphLayoutH.setObjectName(_fromUtf8("graphLayoutH"))
        self.simGraphGroup = QtGui.QGroupBox(RunSummaryWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simGraphGroup.sizePolicy().hasHeightForWidth())
        self.simGraphGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.simGraphGroup.setFont(font)
        self.simGraphGroup.setFlat(False)
        self.simGraphGroup.setObjectName(_fromUtf8("simGraphGroup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.simGraphGroup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.simGraphGraphics = PlotWidget(self.simGraphGroup)
        self.simGraphGraphics.setObjectName(_fromUtf8("simGraphGraphics"))
        self.verticalLayout.addWidget(self.simGraphGraphics)
        self.legendLabel = QtGui.QLabel(self.simGraphGroup)
        self.legendLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.legendLabel.setObjectName(_fromUtf8("legendLabel"))
        self.verticalLayout.addWidget(self.legendLabel)
        self.graphLayoutH.addWidget(self.simGraphGroup)
        self.verticalLayout_2.addLayout(self.graphLayoutH)

        self.retranslateUi(RunSummaryWidget)
        QtCore.QMetaObject.connectSlotsByName(RunSummaryWidget)

    def retranslateUi(self, RunSummaryWidget):
        RunSummaryWidget.setWindowTitle(_translate("RunSummaryWidget", "Form", None))
        self.overviewGroup.setTitle(_translate("RunSummaryWidget", "Overview", None))
        self.overviewLabel.setText(_translate("RunSummaryWidget", "<html><head/><body><p>Manage your running models by adding them to the Run Status table and viewing progress in the graph display. Key statistics will be displayed in the table, including the current progress of the model simulation. You can also view the main criteria of the model run graphically in the Simulation Graph window below.</p><p>Add a new .tlf file by clicking Add Log, update or remove an existing log entry with the right-click context menu, or use the Update All button to update all of the entries at once. Clicking on an entry row in the table will update the graph with the details from that log entry.</p></body></html>", None))
        self.runStatusGroup.setTitle(_translate("RunSummaryWidget", "Run status", None))
        self.updateAllStatusButton.setText(_translate("RunSummaryWidget", "Update All", None))
        self.tlfAddButton.setText(_translate("RunSummaryWidget", "Add Log", None))
        self.autoUpdateButton.setText(_translate("RunSummaryWidget", "Auto Update Active Run", None))
        self.showFmpRunCbox.setText(_translate("RunSummaryWidget", "Show FMP Runform when complete", None))
        item = self.runStatusTable.horizontalHeaderItem(0)
        item.setText(_translate("RunSummaryWidget", "GUID", None))
        item = self.runStatusTable.horizontalHeaderItem(1)
        item.setText(_translate("RunSummaryWidget", "NAME", None))
        item = self.runStatusTable.horizontalHeaderItem(2)
        item.setText(_translate("RunSummaryWidget", "MAX_MB", None))
        item = self.runStatusTable.horizontalHeaderItem(3)
        item.setText(_translate("RunSummaryWidget", "MAX_DDV", None))
        item = self.runStatusTable.horizontalHeaderItem(4)
        item.setText(_translate("RunSummaryWidget", "STATUS", None))
        item = self.runStatusTable.horizontalHeaderItem(5)
        item.setText(_translate("RunSummaryWidget", "COMPLETION", None))
        self.simGraphGroup.setTitle(_translate("RunSummaryWidget", "Simulation graph", None))
        self.legendLabel.setText(_translate("RunSummaryWidget", "<html><head/><body><p><span style=\" font-weight:600; color:#000000;\">Legend:</span><span style=\" color:#004eeb;\">   Flow In</span><span style=\" color:#ff0000;\">   Flow Out  </span> DDV   <span style=\" color:#4be100;\">MB</span></p></body></html>", None))

from pyqtgraph import PlotWidget
