# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Query_Widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QueryWidget(object):
    def setupUi(self, QueryWidget):
        QueryWidget.setObjectName(_fromUtf8("QueryWidget"))
        QueryWidget.resize(737, 460)
        self.verticalLayout = QtGui.QVBoxLayout(QueryWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.queryTabWidget = QtGui.QTabWidget(QueryWidget)
        self.queryTabWidget.setMaximumSize(QtCore.QSize(16777215, 180))
        self.queryTabWidget.setObjectName(_fromUtf8("queryTabWidget"))
        self.simpleQueryTab = QtGui.QWidget()
        self.simpleQueryTab.setObjectName(_fromUtf8("simpleQueryTab"))
        self.gridLayout = QtGui.QGridLayout(self.simpleQueryTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.simpleQueryTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.queryRunIdSbox = QtGui.QSpinBox(self.simpleQueryTab)
        self.queryRunIdSbox.setEnabled(False)
        self.queryRunIdSbox.setMinimum(1)
        self.queryRunIdSbox.setMaximum(9999999)
        self.queryRunIdSbox.setObjectName(_fromUtf8("queryRunIdSbox"))
        self.gridLayout_2.addWidget(self.queryRunIdSbox, 1, 1, 1, 1)
        self.queryFilterRunCbox = QtGui.QCheckBox(self.simpleQueryTab)
        self.queryFilterRunCbox.setObjectName(_fromUtf8("queryFilterRunCbox"))
        self.gridLayout_2.addWidget(self.queryFilterRunCbox, 0, 0, 1, 2)
        self.queryFileCheck = QtGui.QCheckBox(self.simpleQueryTab)
        self.queryFileCheck.setChecked(True)
        self.queryFileCheck.setObjectName(_fromUtf8("queryFileCheck"))
        self.gridLayout_2.addWidget(self.queryFileCheck, 2, 0, 1, 2)
        self.queryNewSubOnlyCheck = QtGui.QCheckBox(self.simpleQueryTab)
        self.queryNewSubOnlyCheck.setObjectName(_fromUtf8("queryNewSubOnlyCheck"))
        self.gridLayout_2.addWidget(self.queryNewSubOnlyCheck, 3, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 4, 4, 1)
        self.label_6 = QtGui.QLabel(self.simpleQueryTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.queryFileTextbox = QtGui.QLineEdit(self.simpleQueryTab)
        self.queryFileTextbox.setEnabled(True)
        self.queryFileTextbox.setObjectName(_fromUtf8("queryFileTextbox"))
        self.gridLayout.addWidget(self.queryFileTextbox, 2, 1, 1, 3)
        self.label_3 = QtGui.QLabel(self.simpleQueryTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.queryNewModelOnlyCheck = QtGui.QCheckBox(self.simpleQueryTab)
        self.queryNewModelOnlyCheck.setEnabled(False)
        self.queryNewModelOnlyCheck.setObjectName(_fromUtf8("queryNewModelOnlyCheck"))
        self.gridLayout.addWidget(self.queryNewModelOnlyCheck, 3, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.simpleQueryTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.runSimpleQueryBut = QtGui.QPushButton(self.simpleQueryTab)
        self.runSimpleQueryBut.setObjectName(_fromUtf8("runSimpleQueryBut"))
        self.gridLayout.addWidget(self.runSimpleQueryBut, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.simpleQueryTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.queryModelTextbox = QtGui.QLineEdit(self.simpleQueryTab)
        self.queryModelTextbox.setObjectName(_fromUtf8("queryModelTextbox"))
        self.gridLayout.addWidget(self.queryModelTextbox, 1, 1, 1, 3)
        self.queryTableCbox = QtGui.QComboBox(self.simpleQueryTab)
        self.queryTableCbox.setMinimumSize(QtCore.QSize(150, 0))
        self.queryTableCbox.setObjectName(_fromUtf8("queryTableCbox"))
        self.gridLayout.addWidget(self.queryTableCbox, 0, 1, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.queryTabWidget.addTab(self.simpleQueryTab, _fromUtf8(""))
        self.FileSummaryTab = QtGui.QWidget()
        self.FileSummaryTab.setObjectName(_fromUtf8("FileSummaryTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.FileSummaryTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fileQuerySelectedList = QtGui.QListWidget(self.FileSummaryTab)
        self.fileQuerySelectedList.setMinimumSize(QtCore.QSize(0, 0))
        self.fileQuerySelectedList.setMaximumSize(QtCore.QSize(82, 16777215))
        self.fileQuerySelectedList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileQuerySelectedList.setObjectName(_fromUtf8("fileQuerySelectedList"))
        self.gridLayout_3.addWidget(self.fileQuerySelectedList, 1, 2, 4, 1)
        self.fileQueryAvailableList = QtGui.QListWidget(self.FileSummaryTab)
        self.fileQueryAvailableList.setMaximumSize(QtCore.QSize(82, 16777215))
        self.fileQueryAvailableList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.fileQueryAvailableList.setObjectName(_fromUtf8("fileQueryAvailableList"))
        self.gridLayout_3.addWidget(self.fileQueryAvailableList, 1, 0, 4, 1)
        self.label_8 = QtGui.QLabel(self.FileSummaryTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.FileSummaryTab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.fileQueryAddAllBut = QtGui.QPushButton(self.FileSummaryTab)
        self.fileQueryAddAllBut.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fileQueryAddAllBut.setObjectName(_fromUtf8("fileQueryAddAllBut"))
        self.gridLayout_3.addWidget(self.fileQueryAddAllBut, 1, 1, 1, 1)
        self.fileQueryTcfLine = QtGui.QLineEdit(self.FileSummaryTab)
        self.fileQueryTcfLine.setObjectName(_fromUtf8("fileQueryTcfLine"))
        self.gridLayout_3.addWidget(self.fileQueryTcfLine, 1, 4, 1, 1)
        self.fileQueryRunOptionsLine = QtGui.QLineEdit(self.FileSummaryTab)
        self.fileQueryRunOptionsLine.setObjectName(_fromUtf8("fileQueryRunOptionsLine"))
        self.gridLayout_3.addWidget(self.fileQueryRunOptionsLine, 3, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.FileSummaryTab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 2, 3, 1, 1)
        self.fileQueryRemoveAllBut = QtGui.QPushButton(self.FileSummaryTab)
        self.fileQueryRemoveAllBut.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fileQueryRemoveAllBut.setObjectName(_fromUtf8("fileQueryRemoveAllBut"))
        self.gridLayout_3.addWidget(self.fileQueryRemoveAllBut, 4, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.FileSummaryTab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 3, 3, 1, 1)
        self.fileQueryRemoveSelectedBut = QtGui.QPushButton(self.FileSummaryTab)
        self.fileQueryRemoveSelectedBut.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fileQueryRemoveSelectedBut.setObjectName(_fromUtf8("fileQueryRemoveSelectedBut"))
        self.gridLayout_3.addWidget(self.fileQueryRemoveSelectedBut, 3, 1, 1, 1)
        self.fileQueryAddSelectedBut = QtGui.QPushButton(self.FileSummaryTab)
        self.fileQueryAddSelectedBut.setMaximumSize(QtCore.QSize(50, 16777215))
        self.fileQueryAddSelectedBut.setObjectName(_fromUtf8("fileQueryAddSelectedBut"))
        self.gridLayout_3.addWidget(self.fileQueryAddSelectedBut, 2, 1, 1, 1)
        self.fileQueryIefLine = QtGui.QLineEdit(self.FileSummaryTab)
        self.fileQueryIefLine.setObjectName(_fromUtf8("fileQueryIefLine"))
        self.gridLayout_3.addWidget(self.fileQueryIefLine, 2, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.FileSummaryTab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.FileSummaryTab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 0, 4, 1, 1)
        self.fileQueryRunBut = QtGui.QPushButton(self.FileSummaryTab)
        self.fileQueryRunBut.setMinimumSize(QtCore.QSize(0, 22))
        self.fileQueryRunBut.setObjectName(_fromUtf8("fileQueryRunBut"))
        self.gridLayout_3.addWidget(self.fileQueryRunBut, 4, 5, 1, 1)
        self.queryFilesHighlightCbox = QtGui.QCheckBox(self.FileSummaryTab)
        self.queryFilesHighlightCbox.setChecked(True)
        self.queryFilesHighlightCbox.setObjectName(_fromUtf8("queryFilesHighlightCbox"))
        self.gridLayout_3.addWidget(self.queryFilesHighlightCbox, 4, 4, 1, 1)
        self.queryTabWidget.addTab(self.FileSummaryTab, _fromUtf8(""))
        self.complexQueryTab = QtGui.QWidget()
        self.complexQueryTab.setObjectName(_fromUtf8("complexQueryTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.complexQueryTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.editorLayout = QtGui.QVBoxLayout()
        self.editorLayout.setObjectName(_fromUtf8("editorLayout"))
        self.horizontalLayout.addLayout(self.editorLayout)
        self.complexScriptList = QtGui.QListWidget(self.complexQueryTab)
        self.complexScriptList.setMaximumSize(QtCore.QSize(250, 16777215))
        self.complexScriptList.setObjectName(_fromUtf8("complexScriptList"))
        self.horizontalLayout.addWidget(self.complexScriptList)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.newQueryScriptBut = QtGui.QPushButton(self.complexQueryTab)
        self.newQueryScriptBut.setObjectName(_fromUtf8("newQueryScriptBut"))
        self.verticalLayout_2.addWidget(self.newQueryScriptBut)
        self.saveQueryScriptBut = QtGui.QPushButton(self.complexQueryTab)
        self.saveQueryScriptBut.setObjectName(_fromUtf8("saveQueryScriptBut"))
        self.verticalLayout_2.addWidget(self.saveQueryScriptBut)
        self.loadQueryScriptBut = QtGui.QPushButton(self.complexQueryTab)
        self.loadQueryScriptBut.setObjectName(_fromUtf8("loadQueryScriptBut"))
        self.verticalLayout_2.addWidget(self.loadQueryScriptBut)
        self.runComplexQueryBut = QtGui.QPushButton(self.complexQueryTab)
        self.runComplexQueryBut.setObjectName(_fromUtf8("runComplexQueryBut"))
        self.verticalLayout_2.addWidget(self.runComplexQueryBut)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.queryTabWidget.addTab(self.complexQueryTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.queryTabWidget)
        self.tableQueryGroup = QtGui.QGroupBox(QueryWidget)
        self.tableQueryGroup.setTitle(_fromUtf8(""))
        self.tableQueryGroup.setObjectName(_fromUtf8("tableQueryGroup"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tableQueryGroup)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout.addWidget(self.tableQueryGroup)

        self.retranslateUi(QueryWidget)
        self.queryTabWidget.setCurrentIndex(2)
        QtCore.QObject.connect(self.queryFilterRunCbox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.queryRunIdSbox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(QueryWidget)

    def retranslateUi(self, QueryWidget):
        QueryWidget.setWindowTitle(_translate("QueryWidget", "Form", None))
        self.label_5.setText(_translate("QueryWidget", "Run ID", None))
        self.queryFilterRunCbox.setText(_translate("QueryWidget", "Filter by Run ID", None))
        self.queryFileCheck.setText(_translate("QueryWidget", "Include subfiles", None))
        self.queryNewSubOnlyCheck.setText(_translate("QueryWidget", "New subfiles only", None))
        self.label_6.setText(_translate("QueryWidget", "Where subfile is", None))
        self.label_3.setText(_translate("QueryWidget", "Include % for wildcard (e.g. to match all \'xxv2.xx\' use %v2%)", None))
        self.queryNewModelOnlyCheck.setText(_translate("QueryWidget", "New modelfiles only", None))
        self.label_2.setText(_translate("QueryWidget", "Table", None))
        self.runSimpleQueryBut.setText(_translate("QueryWidget", "Run Query", None))
        self.label_4.setText(_translate("QueryWidget", "Where modelfile/run options is", None))
        self.queryTabWidget.setTabText(self.queryTabWidget.indexOf(self.simpleQueryTab), _translate("QueryWidget", "Simple Query", None))
        self.label_8.setText(_translate("QueryWidget", "Available Run Id\'s", None))
        self.label_9.setText(_translate("QueryWidget", "Selected Run ID\'s", None))
        self.fileQueryAddAllBut.setToolTip(_translate("QueryWidget", "Add all", None))
        self.fileQueryAddAllBut.setText(_translate("QueryWidget", ">>", None))
        self.label_11.setText(_translate("QueryWidget", "Ief", None))
        self.fileQueryRemoveAllBut.setToolTip(_translate("QueryWidget", "Remove all", None))
        self.fileQueryRemoveAllBut.setText(_translate("QueryWidget", "<<", None))
        self.label_12.setText(_translate("QueryWidget", "Run Options", None))
        self.fileQueryRemoveSelectedBut.setToolTip(_translate("QueryWidget", "Remove selected", None))
        self.fileQueryRemoveSelectedBut.setText(_translate("QueryWidget", "<", None))
        self.fileQueryAddSelectedBut.setToolTip(_translate("QueryWidget", "Add selected", None))
        self.fileQueryAddSelectedBut.setText(_translate("QueryWidget", ">", None))
        self.label_10.setText(_translate("QueryWidget", "Tcf", None))
        self.label_13.setText(_translate("QueryWidget", "Click ID in list boxes to show summary details", None))
        self.fileQueryRunBut.setText(_translate("QueryWidget", "Run Query", None))
        self.queryFilesHighlightCbox.setText(_translate("QueryWidget", "Highlight new files", None))
        self.queryTabWidget.setTabText(self.queryTabWidget.indexOf(self.FileSummaryTab), _translate("QueryWidget", "Model File Query", None))
        self.newQueryScriptBut.setText(_translate("QueryWidget", "New Script", None))
        self.saveQueryScriptBut.setText(_translate("QueryWidget", "Save Script", None))
        self.loadQueryScriptBut.setText(_translate("QueryWidget", "Load Script", None))
        self.runComplexQueryBut.setText(_translate("QueryWidget", "Run Query", None))
        self.queryTabWidget.setTabText(self.queryTabWidget.indexOf(self.complexQueryTab), _translate("QueryWidget", "Custom Query", None))

