# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\query\Query_Widget_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QueryWidget(object):
    def setupUi(self, QueryWidget):
        QueryWidget.setObjectName("QueryWidget")
        QueryWidget.resize(781, 443)
        self.verticalLayout = QtWidgets.QVBoxLayout(QueryWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.queryTabWidget = QtWidgets.QTabWidget(QueryWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryTabWidget.sizePolicy().hasHeightForWidth())
        self.queryTabWidget.setSizePolicy(sizePolicy)
        self.queryTabWidget.setObjectName("queryTabWidget")
        self.simpleQueryTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.simpleQueryTab.sizePolicy().hasHeightForWidth())
        self.simpleQueryTab.setSizePolicy(sizePolicy)
        self.simpleQueryTab.setObjectName("simpleQueryTab")
        self.gridLayout = QtWidgets.QGridLayout(self.simpleQueryTab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.simpleQueryTab)
        self.label_2.setMinimumSize(QtCore.QSize(170, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_13.addWidget(self.label_2)
        self.queryTableCbox = QtWidgets.QComboBox(self.simpleQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryTableCbox.sizePolicy().hasHeightForWidth())
        self.queryTableCbox.setSizePolicy(sizePolicy)
        self.queryTableCbox.setObjectName("queryTableCbox")
        self.horizontalLayout_13.addWidget(self.queryTableCbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_4 = QtWidgets.QLabel(self.simpleQueryTab)
        self.label_4.setMinimumSize(QtCore.QSize(165, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.queryModelTextbox = QtWidgets.QLineEdit(self.simpleQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryModelTextbox.sizePolicy().hasHeightForWidth())
        self.queryModelTextbox.setSizePolicy(sizePolicy)
        self.queryModelTextbox.setObjectName("queryModelTextbox")
        self.horizontalLayout_16.addWidget(self.queryModelTextbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_6 = QtWidgets.QLabel(self.simpleQueryTab)
        self.label_6.setMinimumSize(QtCore.QSize(165, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_17.addWidget(self.label_6)
        self.queryFileTextbox = QtWidgets.QLineEdit(self.simpleQueryTab)
        self.queryFileTextbox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryFileTextbox.sizePolicy().hasHeightForWidth())
        self.queryFileTextbox.setSizePolicy(sizePolicy)
        self.queryFileTextbox.setObjectName("queryFileTextbox")
        self.horizontalLayout_17.addWidget(self.queryFileTextbox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.runSimpleQueryBut = QtWidgets.QPushButton(self.simpleQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runSimpleQueryBut.sizePolicy().hasHeightForWidth())
        self.runSimpleQueryBut.setSizePolicy(sizePolicy)
        self.runSimpleQueryBut.setObjectName("runSimpleQueryBut")
        self.horizontalLayout_18.addWidget(self.runSimpleQueryBut)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.simpleQueryTab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_18.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.queryFilterRunCbox = QtWidgets.QCheckBox(self.simpleQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryFilterRunCbox.sizePolicy().hasHeightForWidth())
        self.queryFilterRunCbox.setSizePolicy(sizePolicy)
        self.queryFilterRunCbox.setObjectName("queryFilterRunCbox")
        self.verticalLayout_5.addWidget(self.queryFilterRunCbox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.simpleQueryTab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.queryRunIdSbox = QtWidgets.QSpinBox(self.simpleQueryTab)
        self.queryRunIdSbox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryRunIdSbox.sizePolicy().hasHeightForWidth())
        self.queryRunIdSbox.setSizePolicy(sizePolicy)
        self.queryRunIdSbox.setMinimum(1)
        self.queryRunIdSbox.setMaximum(9999999)
        self.queryRunIdSbox.setObjectName("queryRunIdSbox")
        self.horizontalLayout_2.addWidget(self.queryRunIdSbox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.queryFileCheck = QtWidgets.QCheckBox(self.simpleQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryFileCheck.sizePolicy().hasHeightForWidth())
        self.queryFileCheck.setSizePolicy(sizePolicy)
        self.queryFileCheck.setChecked(True)
        self.queryFileCheck.setObjectName("queryFileCheck")
        self.verticalLayout_5.addWidget(self.queryFileCheck)
        self.queryNewSubOnlyCheck = QtWidgets.QCheckBox(self.simpleQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryNewSubOnlyCheck.sizePolicy().hasHeightForWidth())
        self.queryNewSubOnlyCheck.setSizePolicy(sizePolicy)
        self.queryNewSubOnlyCheck.setObjectName("queryNewSubOnlyCheck")
        self.verticalLayout_5.addWidget(self.queryNewSubOnlyCheck)
        self.queryNewModelOnlyCheck = QtWidgets.QCheckBox(self.simpleQueryTab)
        self.queryNewModelOnlyCheck.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryNewModelOnlyCheck.sizePolicy().hasHeightForWidth())
        self.queryNewModelOnlyCheck.setSizePolicy(sizePolicy)
        self.queryNewModelOnlyCheck.setObjectName("queryNewModelOnlyCheck")
        self.verticalLayout_5.addWidget(self.queryNewModelOnlyCheck)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.queryTabWidget.addTab(self.simpleQueryTab, "")
        self.FileSummaryTab = QtWidgets.QWidget()
        self.FileSummaryTab.setObjectName("FileSummaryTab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.FileSummaryTab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_9.setSpacing(4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_15.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_15.addWidget(self.label_9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.fileQueryAvailableList = QtWidgets.QListWidget(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryAvailableList.sizePolicy().hasHeightForWidth())
        self.fileQueryAvailableList.setSizePolicy(sizePolicy)
        self.fileQueryAvailableList.setMinimumSize(QtCore.QSize(0, 100))
        self.fileQueryAvailableList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.fileQueryAvailableList.setObjectName("fileQueryAvailableList")
        self.horizontalLayout_14.addWidget(self.fileQueryAvailableList)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.fileQueryAddAllBut = QtWidgets.QPushButton(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryAddAllBut.sizePolicy().hasHeightForWidth())
        self.fileQueryAddAllBut.setSizePolicy(sizePolicy)
        self.fileQueryAddAllBut.setObjectName("fileQueryAddAllBut")
        self.verticalLayout_7.addWidget(self.fileQueryAddAllBut)
        self.fileQueryAddSelectedBut = QtWidgets.QPushButton(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryAddSelectedBut.sizePolicy().hasHeightForWidth())
        self.fileQueryAddSelectedBut.setSizePolicy(sizePolicy)
        self.fileQueryAddSelectedBut.setObjectName("fileQueryAddSelectedBut")
        self.verticalLayout_7.addWidget(self.fileQueryAddSelectedBut)
        self.fileQueryRemoveSelectedBut = QtWidgets.QPushButton(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryRemoveSelectedBut.sizePolicy().hasHeightForWidth())
        self.fileQueryRemoveSelectedBut.setSizePolicy(sizePolicy)
        self.fileQueryRemoveSelectedBut.setObjectName("fileQueryRemoveSelectedBut")
        self.verticalLayout_7.addWidget(self.fileQueryRemoveSelectedBut)
        self.fileQueryRemoveAllBut = QtWidgets.QPushButton(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryRemoveAllBut.sizePolicy().hasHeightForWidth())
        self.fileQueryRemoveAllBut.setSizePolicy(sizePolicy)
        self.fileQueryRemoveAllBut.setObjectName("fileQueryRemoveAllBut")
        self.verticalLayout_7.addWidget(self.fileQueryRemoveAllBut)
        self.horizontalLayout_14.addLayout(self.verticalLayout_7)
        self.fileQuerySelectedList = QtWidgets.QListWidget(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQuerySelectedList.sizePolicy().hasHeightForWidth())
        self.fileQuerySelectedList.setSizePolicy(sizePolicy)
        self.fileQuerySelectedList.setMinimumSize(QtCore.QSize(0, 100))
        self.fileQuerySelectedList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.fileQuerySelectedList.setObjectName("fileQuerySelectedList")
        self.horizontalLayout_14.addWidget(self.fileQuerySelectedList)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.verticalLayout_9.setStretch(0, 3)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.FileSummaryTab)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.FileSummaryTab)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_10.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.FileSummaryTab)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_10.addWidget(self.label_12)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.fileQueryTcfLine = QtWidgets.QLineEdit(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryTcfLine.sizePolicy().hasHeightForWidth())
        self.fileQueryTcfLine.setSizePolicy(sizePolicy)
        self.fileQueryTcfLine.setObjectName("fileQueryTcfLine")
        self.verticalLayout_13.addWidget(self.fileQueryTcfLine)
        self.fileQueryIefLine = QtWidgets.QLineEdit(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryIefLine.sizePolicy().hasHeightForWidth())
        self.fileQueryIefLine.setSizePolicy(sizePolicy)
        self.fileQueryIefLine.setObjectName("fileQueryIefLine")
        self.verticalLayout_13.addWidget(self.fileQueryIefLine)
        self.fileQueryRunOptionsLine = QtWidgets.QLineEdit(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryRunOptionsLine.sizePolicy().hasHeightForWidth())
        self.fileQueryRunOptionsLine.setSizePolicy(sizePolicy)
        self.fileQueryRunOptionsLine.setObjectName("fileQueryRunOptionsLine")
        self.verticalLayout_13.addWidget(self.fileQueryRunOptionsLine)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.queryFilesHighlightCbox = QtWidgets.QCheckBox(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryFilesHighlightCbox.sizePolicy().hasHeightForWidth())
        self.queryFilesHighlightCbox.setSizePolicy(sizePolicy)
        self.queryFilesHighlightCbox.setChecked(True)
        self.queryFilesHighlightCbox.setObjectName("queryFilesHighlightCbox")
        self.horizontalLayout_3.addWidget(self.queryFilesHighlightCbox)
        self.fileQueryRunBut = QtWidgets.QPushButton(self.FileSummaryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileQueryRunBut.sizePolicy().hasHeightForWidth())
        self.fileQueryRunBut.setSizePolicy(sizePolicy)
        self.fileQueryRunBut.setObjectName("fileQueryRunBut")
        self.horizontalLayout_3.addWidget(self.fileQueryRunBut)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.verticalLayout_11.setStretch(0, 7)
        self.horizontalLayout_8.addLayout(self.verticalLayout_11)
        self.queryTabWidget.addTab(self.FileSummaryTab, "")
        self.complexQueryTab = QtWidgets.QWidget()
        self.complexQueryTab.setObjectName("complexQueryTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.complexQueryTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editorLayout = QtWidgets.QVBoxLayout()
        self.editorLayout.setSpacing(0)
        self.editorLayout.setObjectName("editorLayout")
        self.horizontalLayout.addLayout(self.editorLayout)
        self.complexScriptList = QtWidgets.QListWidget(self.complexQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.complexScriptList.sizePolicy().hasHeightForWidth())
        self.complexScriptList.setSizePolicy(sizePolicy)
        self.complexScriptList.setMinimumSize(QtCore.QSize(0, 100))
        self.complexScriptList.setObjectName("complexScriptList")
        self.horizontalLayout.addWidget(self.complexScriptList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newQueryScriptBut = QtWidgets.QPushButton(self.complexQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newQueryScriptBut.sizePolicy().hasHeightForWidth())
        self.newQueryScriptBut.setSizePolicy(sizePolicy)
        self.newQueryScriptBut.setObjectName("newQueryScriptBut")
        self.verticalLayout_2.addWidget(self.newQueryScriptBut)
        self.saveQueryScriptBut = QtWidgets.QPushButton(self.complexQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveQueryScriptBut.sizePolicy().hasHeightForWidth())
        self.saveQueryScriptBut.setSizePolicy(sizePolicy)
        self.saveQueryScriptBut.setObjectName("saveQueryScriptBut")
        self.verticalLayout_2.addWidget(self.saveQueryScriptBut)
        self.saveAsQueryScriptBut = QtWidgets.QPushButton(self.complexQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAsQueryScriptBut.sizePolicy().hasHeightForWidth())
        self.saveAsQueryScriptBut.setSizePolicy(sizePolicy)
        self.saveAsQueryScriptBut.setObjectName("saveAsQueryScriptBut")
        self.verticalLayout_2.addWidget(self.saveAsQueryScriptBut)
        self.loadQueryScriptBut = QtWidgets.QPushButton(self.complexQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadQueryScriptBut.sizePolicy().hasHeightForWidth())
        self.loadQueryScriptBut.setSizePolicy(sizePolicy)
        self.loadQueryScriptBut.setObjectName("loadQueryScriptBut")
        self.verticalLayout_2.addWidget(self.loadQueryScriptBut)
        self.runComplexQueryBut = QtWidgets.QPushButton(self.complexQueryTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runComplexQueryBut.sizePolicy().hasHeightForWidth())
        self.runComplexQueryBut.setSizePolicy(sizePolicy)
        self.runComplexQueryBut.setObjectName("runComplexQueryBut")
        self.verticalLayout_2.addWidget(self.runComplexQueryBut)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.queryTabWidget.addTab(self.complexQueryTab, "")
        self.verticalLayout.addWidget(self.queryTabWidget)
        self.tableQueryGroup = QtWidgets.QGroupBox(QueryWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableQueryGroup.sizePolicy().hasHeightForWidth())
        self.tableQueryGroup.setSizePolicy(sizePolicy)
        self.tableQueryGroup.setTitle("")
        self.tableQueryGroup.setObjectName("tableQueryGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tableQueryGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout.addWidget(self.tableQueryGroup)

        self.retranslateUi(QueryWidget)
        self.queryTabWidget.setCurrentIndex(0)
        self.queryFilterRunCbox.toggled['bool'].connect(self.queryRunIdSbox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(QueryWidget)

    def retranslateUi(self, QueryWidget):
        _translate = QtCore.QCoreApplication.translate
        QueryWidget.setWindowTitle(_translate("QueryWidget", "Form"))
        self.label_2.setText(_translate("QueryWidget", "Table"))
        self.label_4.setText(_translate("QueryWidget", "Where modelfile/run options is"))
        self.label_6.setText(_translate("QueryWidget", "Where subfile is"))
        self.runSimpleQueryBut.setText(_translate("QueryWidget", "Run Query"))
        self.label_3.setText(_translate("QueryWidget", "Include % for wildcard (e.g. to match all \'xxv2.xx\' use %v2%)"))
        self.queryFilterRunCbox.setText(_translate("QueryWidget", "Filter by Run ID"))
        self.label_5.setText(_translate("QueryWidget", "Run ID"))
        self.queryFileCheck.setText(_translate("QueryWidget", "Include subfiles"))
        self.queryNewSubOnlyCheck.setText(_translate("QueryWidget", "New subfiles only"))
        self.queryNewModelOnlyCheck.setText(_translate("QueryWidget", "New modelfiles only"))
        self.queryTabWidget.setTabText(self.queryTabWidget.indexOf(self.simpleQueryTab), _translate("QueryWidget", "Simple Query"))
        self.label_8.setText(_translate("QueryWidget", "Available Run Id\'s"))
        self.label_9.setText(_translate("QueryWidget", "Selected Run ID\'s"))
        self.fileQueryAddAllBut.setToolTip(_translate("QueryWidget", "Add all"))
        self.fileQueryAddAllBut.setText(_translate("QueryWidget", ">>"))
        self.fileQueryAddSelectedBut.setToolTip(_translate("QueryWidget", "Add selected"))
        self.fileQueryAddSelectedBut.setText(_translate("QueryWidget", ">"))
        self.fileQueryRemoveSelectedBut.setToolTip(_translate("QueryWidget", "Remove selected"))
        self.fileQueryRemoveSelectedBut.setText(_translate("QueryWidget", "<"))
        self.fileQueryRemoveAllBut.setToolTip(_translate("QueryWidget", "Remove all"))
        self.fileQueryRemoveAllBut.setText(_translate("QueryWidget", "<<"))
        self.label_13.setText(_translate("QueryWidget", "Click ID in list boxes to show summary details"))
        self.label_10.setText(_translate("QueryWidget", "Tcf"))
        self.label_11.setText(_translate("QueryWidget", "Ief"))
        self.label_12.setText(_translate("QueryWidget", "Run Options"))
        self.queryFilesHighlightCbox.setText(_translate("QueryWidget", "Highlight new files"))
        self.fileQueryRunBut.setText(_translate("QueryWidget", "Run Query"))
        self.queryTabWidget.setTabText(self.queryTabWidget.indexOf(self.FileSummaryTab), _translate("QueryWidget", "Model File Query"))
        self.newQueryScriptBut.setText(_translate("QueryWidget", "New Script"))
        self.saveQueryScriptBut.setText(_translate("QueryWidget", "Save Script"))
        self.saveAsQueryScriptBut.setText(_translate("QueryWidget", "Save As Script"))
        self.loadQueryScriptBut.setText(_translate("QueryWidget", "Load Script"))
        self.runComplexQueryBut.setText(_translate("QueryWidget", "Run Query"))
        self.queryTabWidget.setTabText(self.queryTabWidget.indexOf(self.complexQueryTab), _translate("QueryWidget", "Custom Query"))
