# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\NewEntry_Widget_qt5.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewEntryWidget(object):
    def setupUi(self, NewEntryWidget):
        NewEntryWidget.setObjectName("NewEntryWidget")
        NewEntryWidget.resize(798, 647)
        self.verticalLayout = QtWidgets.QVBoxLayout(NewEntryWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructionsTextBrowser = QtWidgets.QTextBrowser(NewEntryWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructionsTextBrowser.sizePolicy().hasHeightForWidth())
        self.instructionsTextBrowser.setSizePolicy(sizePolicy)
        self.instructionsTextBrowser.setMinimumSize(QtCore.QSize(0, 150))
        self.instructionsTextBrowser.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.instructionsTextBrowser.setFont(font)
        self.instructionsTextBrowser.setObjectName("instructionsTextBrowser")
        self.verticalLayout.addWidget(self.instructionsTextBrowser)
        self.inputVarGroup = QtWidgets.QGroupBox(NewEntryWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputVarGroup.sizePolicy().hasHeightForWidth())
        self.inputVarGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputVarGroup.setFont(font)
        self.inputVarGroup.setObjectName("inputVarGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.inputVarGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.modellerLabel = QtWidgets.QLabel(self.inputVarGroup)
        self.modellerLabel.setObjectName("modellerLabel")
        self.gridLayout_4.addWidget(self.modellerLabel, 0, 0, 1, 1)
        self.modellerTextbox = QtWidgets.QLineEdit(self.inputVarGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modellerTextbox.sizePolicy().hasHeightForWidth())
        self.modellerTextbox.setSizePolicy(sizePolicy)
        self.modellerTextbox.setObjectName("modellerTextbox")
        self.gridLayout_4.addWidget(self.modellerTextbox, 0, 1, 1, 1)
        self.isisVersionLabel = QtWidgets.QLabel(self.inputVarGroup)
        self.isisVersionLabel.setObjectName("isisVersionLabel")
        self.gridLayout_4.addWidget(self.isisVersionLabel, 0, 2, 1, 1)
        self.isisVersionTextbox = QtWidgets.QLineEdit(self.inputVarGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.isisVersionTextbox.sizePolicy().hasHeightForWidth())
        self.isisVersionTextbox.setSizePolicy(sizePolicy)
        self.isisVersionTextbox.setObjectName("isisVersionTextbox")
        self.gridLayout_4.addWidget(self.isisVersionTextbox, 0, 3, 1, 1)
        self.tuflowVersionLabel = QtWidgets.QLabel(self.inputVarGroup)
        self.tuflowVersionLabel.setObjectName("tuflowVersionLabel")
        self.gridLayout_4.addWidget(self.tuflowVersionLabel, 0, 4, 1, 1)
        self.tuflowVersionTextbox = QtWidgets.QLineEdit(self.inputVarGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tuflowVersionTextbox.sizePolicy().hasHeightForWidth())
        self.tuflowVersionTextbox.setSizePolicy(sizePolicy)
        self.tuflowVersionTextbox.setObjectName("tuflowVersionTextbox")
        self.gridLayout_4.addWidget(self.tuflowVersionTextbox, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 6, 1, 1)
        self.eventNameLabel = QtWidgets.QLabel(self.inputVarGroup)
        self.eventNameLabel.setObjectName("eventNameLabel")
        self.gridLayout_4.addWidget(self.eventNameLabel, 1, 0, 1, 1)
        self.eventNameTextbox = QtWidgets.QLineEdit(self.inputVarGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eventNameTextbox.sizePolicy().hasHeightForWidth())
        self.eventNameTextbox.setSizePolicy(sizePolicy)
        self.eventNameTextbox.setObjectName("eventNameTextbox")
        self.gridLayout_4.addWidget(self.eventNameTextbox, 1, 1, 1, 1)
        self.isisVersionLabel_2 = QtWidgets.QLabel(self.inputVarGroup)
        self.isisVersionLabel_2.setObjectName("isisVersionLabel_2")
        self.gridLayout_4.addWidget(self.isisVersionLabel_2, 1, 2, 1, 1)
        self.runOptionsTextbox = QtWidgets.QLineEdit(self.inputVarGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runOptionsTextbox.sizePolicy().hasHeightForWidth())
        self.runOptionsTextbox.setSizePolicy(sizePolicy)
        self.runOptionsTextbox.setObjectName("runOptionsTextbox")
        self.gridLayout_4.addWidget(self.runOptionsTextbox, 1, 3, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 6, 1, 1)
        self.verticalLayout.addWidget(self.inputVarGroup)
        self.loadModelTab = QtWidgets.QTabWidget(NewEntryWidget)
        self.loadModelTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.loadModelTab.setObjectName("loadModelTab")
        self.loadSingleModelTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSingleModelTab.sizePolicy().hasHeightForWidth())
        self.loadSingleModelTab.setSizePolicy(sizePolicy)
        self.loadSingleModelTab.setMinimumSize(QtCore.QSize(0, 0))
        self.loadSingleModelTab.setObjectName("loadSingleModelTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.loadSingleModelTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadModelGroup = QtWidgets.QGroupBox(self.loadSingleModelTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadModelGroup.sizePolicy().hasHeightForWidth())
        self.loadModelGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial 12")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loadModelGroup.setFont(font)
        self.loadModelGroup.setStyleSheet("")
        self.loadModelGroup.setObjectName("loadModelGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.loadModelGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.loadModelTextbox = QtWidgets.QLineEdit(self.loadModelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadModelTextbox.sizePolicy().hasHeightForWidth())
        self.loadModelTextbox.setSizePolicy(sizePolicy)
        self.loadModelTextbox.setObjectName("loadModelTextbox")
        self.gridLayout.addWidget(self.loadModelTextbox, 1, 0, 1, 2)
        self.loadModelButton = QtWidgets.QPushButton(self.loadModelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadModelButton.sizePolicy().hasHeightForWidth())
        self.loadModelButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.loadModelButton.setFont(font)
        self.loadModelButton.setObjectName("loadModelButton")
        self.gridLayout.addWidget(self.loadModelButton, 1, 2, 1, 1)
        self.loadModelComboLabel = QtWidgets.QLabel(self.loadModelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadModelComboLabel.sizePolicy().hasHeightForWidth())
        self.loadModelComboLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loadModelComboLabel.setFont(font)
        self.loadModelComboLabel.setObjectName("loadModelComboLabel")
        self.gridLayout.addWidget(self.loadModelComboLabel, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.loadModelGroup)
        spacerItem2 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.submitSingleModelGroup = QtWidgets.QGroupBox(self.loadSingleModelTab)
        self.submitSingleModelGroup.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitSingleModelGroup.sizePolicy().hasHeightForWidth())
        self.submitSingleModelGroup.setSizePolicy(sizePolicy)
        self.submitSingleModelGroup.setObjectName("submitSingleModelGroup")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.submitSingleModelGroup)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.submitSingleModelLabel = QtWidgets.QLabel(self.submitSingleModelGroup)
        self.submitSingleModelLabel.setObjectName("submitSingleModelLabel")
        self.verticalLayout_23.addWidget(self.submitSingleModelLabel)
        self.addSingleLogEntryButton = QtWidgets.QPushButton(self.submitSingleModelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addSingleLogEntryButton.sizePolicy().hasHeightForWidth())
        self.addSingleLogEntryButton.setSizePolicy(sizePolicy)
        self.addSingleLogEntryButton.setObjectName("addSingleLogEntryButton")
        self.verticalLayout_23.addWidget(self.addSingleLogEntryButton)
        self.horizontalLayout_3.addWidget(self.submitSingleModelGroup)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.modelEntryTreeView = QtWidgets.QTreeView(self.loadSingleModelTab)
        self.modelEntryTreeView.setMinimumSize(QtCore.QSize(0, 0))
        self.modelEntryTreeView.setAlternatingRowColors(True)
        self.modelEntryTreeView.setObjectName("modelEntryTreeView")
        self.verticalLayout_2.addWidget(self.modelEntryTreeView)
        self.loadModelTab.addTab(self.loadSingleModelTab, "")
        self.multiModelLoadTab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiModelLoadTab.sizePolicy().hasHeightForWidth())
        self.multiModelLoadTab.setSizePolicy(sizePolicy)
        self.multiModelLoadTab.setMinimumSize(QtCore.QSize(0, 0))
        self.multiModelLoadTab.setObjectName("multiModelLoadTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.multiModelLoadTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chooseMultipleModelsGroupBox = QtWidgets.QGroupBox(self.multiModelLoadTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseMultipleModelsGroupBox.sizePolicy().hasHeightForWidth())
        self.chooseMultipleModelsGroupBox.setSizePolicy(sizePolicy)
        self.chooseMultipleModelsGroupBox.setAutoFillBackground(False)
        self.chooseMultipleModelsGroupBox.setObjectName("chooseMultipleModelsGroupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.chooseMultipleModelsGroupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label = QtWidgets.QLabel(self.chooseMultipleModelsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 0, 1, 1)
        self.multipleModelLayoutH = QtWidgets.QHBoxLayout()
        self.multipleModelLayoutH.setObjectName("multipleModelLayoutH")
        self.multipleModelLayoutV = QtWidgets.QVBoxLayout()
        self.multipleModelLayoutV.setObjectName("multipleModelLayoutV")
        self.addMultiModelButton = QtWidgets.QPushButton(self.chooseMultipleModelsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMultiModelButton.sizePolicy().hasHeightForWidth())
        self.addMultiModelButton.setSizePolicy(sizePolicy)
        self.addMultiModelButton.setMinimumSize(QtCore.QSize(0, 20))
        self.addMultiModelButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/add_icon_25x25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addMultiModelButton.setIcon(icon)
        self.addMultiModelButton.setObjectName("addMultiModelButton")
        self.multipleModelLayoutV.addWidget(self.addMultiModelButton)
        self.removeMultiModelButton = QtWidgets.QPushButton(self.chooseMultipleModelsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeMultiModelButton.sizePolicy().hasHeightForWidth())
        self.removeMultiModelButton.setSizePolicy(sizePolicy)
        self.removeMultiModelButton.setMinimumSize(QtCore.QSize(0, 20))
        self.removeMultiModelButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/delete_icon_25x25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeMultiModelButton.setIcon(icon1)
        self.removeMultiModelButton.setObjectName("removeMultiModelButton")
        self.multipleModelLayoutV.addWidget(self.removeMultiModelButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.multipleModelLayoutV.addItem(spacerItem3)
        self.multipleModelLayoutH.addLayout(self.multipleModelLayoutV)
        self.gridLayout_5.addLayout(self.multipleModelLayoutH, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.chooseMultipleModelsGroupBox, 0, 0, 2, 1)
        self.submitMultiModelGroup = QtWidgets.QGroupBox(self.multiModelLoadTab)
        self.submitMultiModelGroup.setEnabled(False)
        self.submitMultiModelGroup.setObjectName("submitMultiModelGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.submitMultiModelGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.submitMultiModelLabel = QtWidgets.QLabel(self.submitMultiModelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitMultiModelLabel.sizePolicy().hasHeightForWidth())
        self.submitMultiModelLabel.setSizePolicy(sizePolicy)
        self.submitMultiModelLabel.setWordWrap(True)
        self.submitMultiModelLabel.setObjectName("submitMultiModelLabel")
        self.gridLayout_3.addWidget(self.submitMultiModelLabel, 0, 0, 1, 2)
        self.addMultiLogEntryButton = QtWidgets.QPushButton(self.submitMultiModelGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addMultiLogEntryButton.sizePolicy().hasHeightForWidth())
        self.addMultiLogEntryButton.setSizePolicy(sizePolicy)
        self.addMultiLogEntryButton.setObjectName("addMultiLogEntryButton")
        self.gridLayout_3.addWidget(self.addMultiLogEntryButton, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.submitMultiModelGroup, 0, 1, 1, 1)
        self.multiModelLoadErrorGroup = QtWidgets.QGroupBox(self.multiModelLoadTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiModelLoadErrorGroup.sizePolicy().hasHeightForWidth())
        self.multiModelLoadErrorGroup.setSizePolicy(sizePolicy)
        self.multiModelLoadErrorGroup.setMinimumSize(QtCore.QSize(160, 0))
        self.multiModelLoadErrorGroup.setMaximumSize(QtCore.QSize(360, 16777215))
        self.multiModelLoadErrorGroup.setObjectName("multiModelLoadErrorGroup")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.multiModelLoadErrorGroup)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.multiModelErrorCopyButton = QtWidgets.QPushButton(self.multiModelLoadErrorGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiModelErrorCopyButton.sizePolicy().hasHeightForWidth())
        self.multiModelErrorCopyButton.setSizePolicy(sizePolicy)
        self.multiModelErrorCopyButton.setObjectName("multiModelErrorCopyButton")
        self.horizontalLayout_6.addWidget(self.multiModelErrorCopyButton)
        self.multiModelErrorClearButton = QtWidgets.QPushButton(self.multiModelLoadErrorGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiModelErrorClearButton.sizePolicy().hasHeightForWidth())
        self.multiModelErrorClearButton.setSizePolicy(sizePolicy)
        self.multiModelErrorClearButton.setObjectName("multiModelErrorClearButton")
        self.horizontalLayout_6.addWidget(self.multiModelErrorClearButton)
        spacerItem5 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_27.addLayout(self.horizontalLayout_6)
        self.multiModelLoadErrorTextEdit = QtWidgets.QTextEdit(self.multiModelLoadErrorGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.multiModelLoadErrorTextEdit.sizePolicy().hasHeightForWidth())
        self.multiModelLoadErrorTextEdit.setSizePolicy(sizePolicy)
        self.multiModelLoadErrorTextEdit.setObjectName("multiModelLoadErrorTextEdit")
        self.verticalLayout_27.addWidget(self.multiModelLoadErrorTextEdit)
        self.gridLayout_2.addWidget(self.multiModelLoadErrorGroup, 1, 1, 1, 1)
        self.chooseMultipleModelsGroupBox.raise_()
        self.multiModelLoadErrorGroup.raise_()
        self.submitMultiModelGroup.raise_()
        self.loadModelTab.addTab(self.multiModelLoadTab, "")
        self.verticalLayout.addWidget(self.loadModelTab)

        self.retranslateUi(NewEntryWidget)
        self.loadModelTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NewEntryWidget)

    def retranslateUi(self, NewEntryWidget):
        _translate = QtCore.QCoreApplication.translate
        NewEntryWidget.setWindowTitle(_translate("NewEntryWidget", "Form"))
        self.instructionsTextBrowser.setHtml(_translate("NewEntryWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/icons/Logit_Logo2_75x75.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">LogIT is an automatic logging tool for ISIS/Flood Modeller Pro and TUFLOW.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Duncan R. 2016.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:6pt; font-weight:600; color:#ffffff;\">l</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; color:#0055ff;\">Using LogIT</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600; color:#0055ff;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">1) Create new log database:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> File &gt; Create New Model Log.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">2) Input Log Variables box:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Insert global log details.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">3) Single / Multiple model load</span><span style=\" font-family:\'MS Shell Dlg 2\';\">: Choose tab and follow the choices below.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Single Model Load:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">1) Load Model:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Click Load Model button in Load Model box; browse models.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">2) Edit variables:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> if you want (green are editable).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">3) Add to log:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Click Add New Log Entry.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Multiple Model Load:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">1) Select models:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Click &quot;+&quot; button to add files.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">         -&gt; Click &quot;X&quot; to remove files.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">2) Add models:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Click Add All Log Entries.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">View Log:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Click View Log tab</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Edit Log:</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> Right-click rows in log.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600; color:#aa0000;\">For more information see the Help tab.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.inputVarGroup.setTitle(_translate("NewEntryWidget", "Input Log Variables"))
        self.modellerLabel.setText(_translate("NewEntryWidget", "Modeller"))
        self.isisVersionLabel.setText(_translate("NewEntryWidget", "Isis Version"))
        self.tuflowVersionLabel.setText(_translate("NewEntryWidget", "Tuflow Version"))
        self.eventNameLabel.setText(_translate("NewEntryWidget", "Event Name"))
        self.isisVersionLabel_2.setText(_translate("NewEntryWidget", "Run Options"))
        self.loadModelGroup.setTitle(_translate("NewEntryWidget", "Load Model "))
        self.loadModelButton.setToolTip(_translate("NewEntryWidget", "Load an IEF or TCF file (Ctrl-L)"))
        self.loadModelButton.setText(_translate("NewEntryWidget", "Load Model..."))
        self.loadModelComboLabel.setText(_translate("NewEntryWidget", "Select an ISIS/FMP ief file or a TUFLOW tcf file to load"))
        self.submitSingleModelGroup.setTitle(_translate("NewEntryWidget", "Submit Model"))
        self.submitSingleModelLabel.setToolTip(_translate("NewEntryWidget", "<html><head/><body><p>Button will be activated when a model has been loaded.</p></body></html>"))
        self.submitSingleModelLabel.setText(_translate("NewEntryWidget", "Click Button to submit the currently \n"
"loaded model to the log database."))
        self.addSingleLogEntryButton.setToolTip(_translate("NewEntryWidget", "Add loaded model data to database (Ctrl-A)"))
        self.addSingleLogEntryButton.setText(_translate("NewEntryWidget", "Add New Log Entry"))
        self.loadModelTab.setTabText(self.loadModelTab.indexOf(self.loadSingleModelTab), _translate("NewEntryWidget", "Single Model Load"))
        self.chooseMultipleModelsGroupBox.setTitle(_translate("NewEntryWidget", "Select Multiple Models"))
        self.label.setText(_translate("NewEntryWidget", "Select the models that you would like to load into the log database using the list below. Add additional models using the add button (+) and remove models using the delete button (x). You can add multiple models at once by holding Ctrl or Shift while clicking with the mouse, and remove multiple models by selecting the check box to the left of the entry and clicking the remove button.\n"
"When done click the Add All Log Entries button. Any errors will be written to the Error Logs window to the right."))
        self.submitMultiModelGroup.setToolTip(_translate("NewEntryWidget", "<html><head/><body><p>Button will be activated when a model has been added to the list.</p></body></html>"))
        self.submitMultiModelGroup.setTitle(_translate("NewEntryWidget", "Submit Model"))
        self.submitMultiModelLabel.setText(_translate("NewEntryWidget", "Click Button to submit all of the models in the list to the database."))
        self.addMultiLogEntryButton.setToolTip(_translate("NewEntryWidget", "Add loaded model data to database (Ctrl-A)"))
        self.addMultiLogEntryButton.setText(_translate("NewEntryWidget", "Add All Log Entries"))
        self.multiModelLoadErrorGroup.setTitle(_translate("NewEntryWidget", "Error logs"))
        self.multiModelErrorCopyButton.setText(_translate("NewEntryWidget", "Copy to Clipboard"))
        self.multiModelErrorClearButton.setText(_translate("NewEntryWidget", "Clear"))
        self.loadModelTab.setTabText(self.loadModelTab.indexOf(self.multiModelLoadTab), _translate("NewEntryWidget", "Multiple Model Load"))
import LogIT_RC_qt5_rc
