# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\extractmodel\ModelExtractor_Widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ExtractModelWidget(object):
    def setupUi(self, ExtractModelWidget):
        ExtractModelWidget.setObjectName(_fromUtf8("ExtractModelWidget"))
        ExtractModelWidget.resize(724, 660)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ExtractModelWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(ExtractModelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setScaledContents(False)
        self.label.setWordWrap(True)
        self.label.setIndent(2)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.inputBox = QtGui.QGroupBox(ExtractModelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.inputBox.sizePolicy().hasHeightForWidth())
        self.inputBox.setSizePolicy(sizePolicy)
        self.inputBox.setObjectName(_fromUtf8("inputBox"))
        self.gridLayout = QtGui.QGridLayout(self.inputBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.extractOutputLabel = QtGui.QLabel(self.inputBox)
        self.extractOutputLabel.setObjectName(_fromUtf8("extractOutputLabel"))
        self.gridLayout.addWidget(self.extractOutputLabel, 2, 0, 1, 1)
        self.extractOutputTextbox = QtGui.QLineEdit(self.inputBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extractOutputTextbox.sizePolicy().hasHeightForWidth())
        self.extractOutputTextbox.setSizePolicy(sizePolicy)
        self.extractOutputTextbox.setObjectName(_fromUtf8("extractOutputTextbox"))
        self.gridLayout.addWidget(self.extractOutputTextbox, 2, 1, 1, 1)
        self.extractOutputButton = QtGui.QPushButton(self.inputBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extractOutputButton.sizePolicy().hasHeightForWidth())
        self.extractOutputButton.setSizePolicy(sizePolicy)
        self.extractOutputButton.setObjectName(_fromUtf8("extractOutputButton"))
        self.gridLayout.addWidget(self.extractOutputButton, 2, 2, 1, 1)
        self.modelTable = QtGui.QTableWidget(self.inputBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelTable.sizePolicy().hasHeightForWidth())
        self.modelTable.setSizePolicy(sizePolicy)
        self.modelTable.setObjectName(_fromUtf8("modelTable"))
        self.modelTable.setColumnCount(3)
        self.modelTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.modelTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.modelTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.modelTable.setHorizontalHeaderItem(2, item)
        self.modelTable.horizontalHeader().setDefaultSectionSize(150)
        self.modelTable.horizontalHeader().setStretchLastSection(True)
        self.modelTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.modelTable, 0, 1, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.inputBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.addModelBut = QtGui.QPushButton(self.inputBox)
        self.addModelBut.setObjectName(_fromUtf8("addModelBut"))
        self.verticalLayout_3.addWidget(self.addModelBut)
        self.removeModelBut = QtGui.QPushButton(self.inputBox)
        self.removeModelBut.setObjectName(_fromUtf8("removeModelBut"))
        self.verticalLayout_3.addWidget(self.removeModelBut)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.inputBox)
        self.modelExtractorGroup = QtGui.QGroupBox(ExtractModelWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.modelExtractorGroup.sizePolicy().hasHeightForWidth())
        self.modelExtractorGroup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial 12"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.modelExtractorGroup.setFont(font)
        self.modelExtractorGroup.setObjectName(_fromUtf8("modelExtractorGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.modelExtractorGroup)
        self.gridLayout_2.setContentsMargins(-1, 16, -1, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.extractOutputTextArea = QtGui.QTextEdit(self.modelExtractorGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extractOutputTextArea.sizePolicy().hasHeightForWidth())
        self.extractOutputTextArea.setSizePolicy(sizePolicy)
        self.extractOutputTextArea.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.extractOutputTextArea.setObjectName(_fromUtf8("extractOutputTextArea"))
        self.gridLayout_2.addWidget(self.extractOutputTextArea, 2, 0, 1, 3)
        self.extractModelButton = QtGui.QPushButton(self.modelExtractorGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extractModelButton.sizePolicy().hasHeightForWidth())
        self.extractModelButton.setSizePolicy(sizePolicy)
        self.extractModelButton.setObjectName(_fromUtf8("extractModelButton"))
        self.gridLayout_2.addWidget(self.extractModelButton, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 2, 1, 1)
        self.extractorHardcodeFilesCbox = QtGui.QCheckBox(self.modelExtractorGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extractorHardcodeFilesCbox.sizePolicy().hasHeightForWidth())
        self.extractorHardcodeFilesCbox.setSizePolicy(sizePolicy)
        self.extractorHardcodeFilesCbox.setObjectName(_fromUtf8("extractorHardcodeFilesCbox"))
        self.gridLayout_2.addWidget(self.extractorHardcodeFilesCbox, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.modelExtractorGroup)

        self.retranslateUi(ExtractModelWidget)
        QtCore.QMetaObject.connectSlotsByName(ExtractModelWidget)

    def retranslateUi(self, ExtractModelWidget):
        ExtractModelWidget.setWindowTitle(_translate("ExtractModelWidget", "Form", None))
        self.groupBox.setTitle(_translate("ExtractModelWidget", "Overview", None))
        self.label.setText(_translate("ExtractModelWidget", "Extract all of the files associated with a model into another directory. Either browse for a model file (.ief or .tcf) in the inputs group or right-click on an logged entry in the Run table and select \'Send to Tool > Extract model\'. If using the right-click menu any run options should be automatically written to the text box, or you can enter them manually. These will be needed if placeholders are used in filenames in order to locate results, checkfiles, and log files. If  the model contains scenario and event logic and you would like to create standard hardcoded control files for delivery check the box.\n"
"\n"
"Any issues with exporting the model, including missing files, or files that could not be copied, will be recorded in the text box.", None))
        self.inputBox.setTitle(_translate("ExtractModelWidget", "Inputs", None))
        self.extractOutputLabel.setText(_translate("ExtractModelWidget", "Output folder", None))
        self.extractOutputButton.setText(_translate("ExtractModelWidget", "Browse...", None))
        item = self.modelTable.horizontalHeaderItem(0)
        item.setText(_translate("ExtractModelWidget", "Folder Name", None))
        item = self.modelTable.horizontalHeaderItem(1)
        item.setText(_translate("ExtractModelWidget", "Run Options", None))
        item = self.modelTable.horizontalHeaderItem(2)
        item.setText(_translate("ExtractModelWidget", "Model Path", None))
        self.label_3.setText(_translate("ExtractModelWidget", "Models to extract", None))
        self.addModelBut.setText(_translate("ExtractModelWidget", "Add Model", None))
        self.removeModelBut.setText(_translate("ExtractModelWidget", "Remove", None))
        self.modelExtractorGroup.setTitle(_translate("ExtractModelWidget", "Model extractor", None))
        self.extractModelButton.setText(_translate("ExtractModelWidget", "Extract Model", None))
        self.extractorHardcodeFilesCbox.setText(_translate("ExtractModelWidget", "Hardcode output files", None))

