# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogIT_UI.ui'
#
# Created: Thu Nov 20 13:29:39 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(680, 605)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(500, 530))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/Logit_Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("QGroupBox {\n"
"    font: 75 9pt \"Arial\" bold;\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"QGroupBox::title { \n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
" } "))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(238, 238, 238);"))
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.newEntryTab = QtGui.QWidget()
        self.newEntryTab.setObjectName(_fromUtf8("newEntryTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.newEntryTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.newEntryTab)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 400))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 619, 754))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.loadModelGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.loadModelGroup.setMinimumSize(QtCore.QSize(0, 100))
        self.loadModelGroup.setMaximumSize(QtCore.QSize(600, 120))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial 12"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.loadModelGroup.setFont(font)
        self.loadModelGroup.setStyleSheet(_fromUtf8(""))
        self.loadModelGroup.setObjectName(_fromUtf8("loadModelGroup"))
        self.gridLayout = QtGui.QGridLayout(self.loadModelGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.loadModelComboFrame = QtGui.QFrame(self.loadModelGroup)
        self.loadModelComboFrame.setMinimumSize(QtCore.QSize(575, 0))
        self.loadModelComboFrame.setMaximumSize(QtCore.QSize(16777215, 35))
        self.loadModelComboFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.loadModelComboFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.loadModelComboFrame.setObjectName(_fromUtf8("loadModelComboFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.loadModelComboFrame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.loadModelComboLabel = QtGui.QLabel(self.loadModelComboFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loadModelComboLabel.setFont(font)
        self.loadModelComboLabel.setObjectName(_fromUtf8("loadModelComboLabel"))
        self.horizontalLayout.addWidget(self.loadModelComboLabel)
        self.loadModelComboBox = QtGui.QComboBox(self.loadModelComboFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadModelComboBox.sizePolicy().hasHeightForWidth())
        self.loadModelComboBox.setSizePolicy(sizePolicy)
        self.loadModelComboBox.setMinimumSize(QtCore.QSize(210, 20))
        self.loadModelComboBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.loadModelComboBox.setAutoFillBackground(False)
        self.loadModelComboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.loadModelComboBox.setObjectName(_fromUtf8("loadModelComboBox"))
        self.loadModelComboBox.addItem(_fromUtf8(""))
        self.loadModelComboBox.addItem(_fromUtf8(""))
        self.loadModelComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.loadModelComboBox)
        spacerItem = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.loadModelComboFrame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.loadModelGroup)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.loadModelTextbox = QtGui.QLineEdit(self.frame_2)
        self.loadModelTextbox.setMinimumSize(QtCore.QSize(390, 20))
        self.loadModelTextbox.setMaximumSize(QtCore.QSize(470, 16777215))
        self.loadModelTextbox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.loadModelTextbox.setObjectName(_fromUtf8("loadModelTextbox"))
        self.horizontalLayout_2.addWidget(self.loadModelTextbox)
        self.loadModelButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(55)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadModelButton.sizePolicy().hasHeightForWidth())
        self.loadModelButton.setSizePolicy(sizePolicy)
        self.loadModelButton.setMinimumSize(QtCore.QSize(90, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.loadModelButton.setFont(font)
        self.loadModelButton.setObjectName(_fromUtf8("loadModelButton"))
        self.horizontalLayout_2.addWidget(self.loadModelButton)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.loadModelGroup)
        self.inputVarGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.inputVarGroup.setMinimumSize(QtCore.QSize(600, 100))
        self.inputVarGroup.setMaximumSize(QtCore.QSize(600, 130))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.inputVarGroup.setFont(font)
        self.inputVarGroup.setStyleSheet(_fromUtf8("font: 75 9pt \"Arial\";"))
        self.inputVarGroup.setObjectName(_fromUtf8("inputVarGroup"))
        self.modellerTextbox = QtGui.QLineEdit(self.inputVarGroup)
        self.modellerTextbox.setGeometry(QtCore.QRect(100, 30, 171, 20))
        self.modellerTextbox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(180, 180, 180);"))
        self.modellerTextbox.setObjectName(_fromUtf8("modellerTextbox"))
        self.modellerLabel = QtGui.QLabel(self.inputVarGroup)
        self.modellerLabel.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.modellerLabel.setObjectName(_fromUtf8("modellerLabel"))
        self.eventNameLabel = QtGui.QLabel(self.inputVarGroup)
        self.eventNameLabel.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.eventNameLabel.setObjectName(_fromUtf8("eventNameLabel"))
        self.eventNameTextbox = QtGui.QLineEdit(self.inputVarGroup)
        self.eventNameTextbox.setGeometry(QtCore.QRect(100, 60, 171, 20))
        self.eventNameTextbox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(180, 180, 180);"))
        self.eventNameTextbox.setObjectName(_fromUtf8("eventNameTextbox"))
        self.isisVersionLabel = QtGui.QLabel(self.inputVarGroup)
        self.isisVersionLabel.setGeometry(QtCore.QRect(320, 30, 71, 20))
        self.isisVersionLabel.setObjectName(_fromUtf8("isisVersionLabel"))
        self.isisVersionTextbox = QtGui.QLineEdit(self.inputVarGroup)
        self.isisVersionTextbox.setGeometry(QtCore.QRect(412, 30, 171, 20))
        self.isisVersionTextbox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(180, 180, 180);"))
        self.isisVersionTextbox.setObjectName(_fromUtf8("isisVersionTextbox"))
        self.tuflowVersionLabel = QtGui.QLabel(self.inputVarGroup)
        self.tuflowVersionLabel.setGeometry(QtCore.QRect(320, 60, 81, 20))
        self.tuflowVersionLabel.setObjectName(_fromUtf8("tuflowVersionLabel"))
        self.tuflowVersionTextbox = QtGui.QLineEdit(self.inputVarGroup)
        self.tuflowVersionTextbox.setGeometry(QtCore.QRect(412, 60, 171, 20))
        self.tuflowVersionTextbox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(180, 180, 180);"))
        self.tuflowVersionTextbox.setObjectName(_fromUtf8("tuflowVersionTextbox"))
        self.verticalLayout_3.addWidget(self.inputVarGroup)
        self.RunGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.RunGroup.setMinimumSize(QtCore.QSize(400, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.RunGroup.setFont(font)
        self.RunGroup.setStyleSheet(_fromUtf8("font: 75 9pt \"Arial\";"))
        self.RunGroup.setObjectName(_fromUtf8("RunGroup"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.RunGroup)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.runEntryTable = QtGui.QTableWidget(self.RunGroup)
        self.runEntryTable.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.runEntryTable.setFont(font)
        self.runEntryTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.runEntryTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.runEntryTable.setObjectName(_fromUtf8("runEntryTable"))
        self.runEntryTable.setColumnCount(17)
        self.runEntryTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.runEntryTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 15, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryTable.setItem(0, 16, item)
        self.verticalLayout_4.addWidget(self.runEntryTable)
        self.verticalLayout_3.addWidget(self.RunGroup)
        self.tgcGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.tgcGroup.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tgcGroup.setFont(font)
        self.tgcGroup.setStyleSheet(_fromUtf8("font: 75 9pt \"Arial\";"))
        self.tgcGroup.setObjectName(_fromUtf8("tgcGroup"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tgcGroup)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tgcEntryTable = QtGui.QTableWidget(self.tgcGroup)
        self.tgcEntryTable.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tgcEntryTable.setFont(font)
        self.tgcEntryTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.tgcEntryTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.tgcEntryTable.setObjectName(_fromUtf8("tgcEntryTable"))
        self.tgcEntryTable.setColumnCount(4)
        self.tgcEntryTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryTable.setItem(0, 3, item)
        self.verticalLayout_5.addWidget(self.tgcEntryTable)
        self.verticalLayout_3.addWidget(self.tgcGroup)
        self.tbcGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.tbcGroup.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.tbcGroup.setFont(font)
        self.tbcGroup.setStyleSheet(_fromUtf8("font: 75 9pt \"Arial\";"))
        self.tbcGroup.setObjectName(_fromUtf8("tbcGroup"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tbcGroup)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tbcEntryTable = QtGui.QTableWidget(self.tbcGroup)
        self.tbcEntryTable.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tbcEntryTable.setFont(font)
        self.tbcEntryTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.tbcEntryTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.tbcEntryTable.setObjectName(_fromUtf8("tbcEntryTable"))
        self.tbcEntryTable.setColumnCount(4)
        self.tbcEntryTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryTable.setItem(0, 3, item)
        self.verticalLayout_6.addWidget(self.tbcEntryTable)
        self.verticalLayout_3.addWidget(self.tbcGroup)
        self.datGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.datGroup.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.datGroup.setFont(font)
        self.datGroup.setStyleSheet(_fromUtf8("font: 75 9pt \"Arial\";"))
        self.datGroup.setObjectName(_fromUtf8("datGroup"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.datGroup)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.datEntryTable = QtGui.QTableWidget(self.datGroup)
        self.datEntryTable.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.datEntryTable.setFont(font)
        self.datEntryTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.datEntryTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.datEntryTable.setObjectName(_fromUtf8("datEntryTable"))
        self.datEntryTable.setColumnCount(4)
        self.datEntryTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryTable.setItem(0, 3, item)
        self.verticalLayout_7.addWidget(self.datEntryTable)
        self.verticalLayout_3.addWidget(self.datGroup)
        self.bcGroup = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.bcGroup.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.bcGroup.setFont(font)
        self.bcGroup.setStyleSheet(_fromUtf8("font: 75 9pt \"Arial\";"))
        self.bcGroup.setObjectName(_fromUtf8("bcGroup"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.bcGroup)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.bcEntryTable = QtGui.QTableWidget(self.bcGroup)
        self.bcEntryTable.setMaximumSize(QtCore.QSize(16777215, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bcEntryTable.setFont(font)
        self.bcEntryTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.bcEntryTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.bcEntryTable.setFrameShadow(QtGui.QFrame.Sunken)
        self.bcEntryTable.setObjectName(_fromUtf8("bcEntryTable"))
        self.bcEntryTable.setColumnCount(4)
        self.bcEntryTable.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryTable.setItem(0, 3, item)
        self.verticalLayout_8.addWidget(self.bcEntryTable)
        self.verticalLayout_3.addWidget(self.bcGroup)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.addLogButtonFrame = QtGui.QFrame(self.newEntryTab)
        self.addLogButtonFrame.setMinimumSize(QtCore.QSize(0, 40))
        self.addLogButtonFrame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.addLogButtonFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.addLogButtonFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.addLogButtonFrame.setObjectName(_fromUtf8("addLogButtonFrame"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.addLogButtonFrame)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.addlogEntryButton = QtGui.QPushButton(self.addLogButtonFrame)
        self.addlogEntryButton.setMinimumSize(QtCore.QSize(0, 25))
        self.addlogEntryButton.setMaximumSize(QtCore.QSize(150, 25))
        self.addlogEntryButton.setSizeIncrement(QtCore.QSize(50, 30))
        self.addlogEntryButton.setObjectName(_fromUtf8("addlogEntryButton"))
        self.verticalLayout_14.addWidget(self.addlogEntryButton)
        self.verticalLayout.addWidget(self.addLogButtonFrame)
        self.tabWidget.addTab(self.newEntryTab, _fromUtf8(""))
        self.viewLogTab = QtGui.QWidget()
        self.viewLogTab.setObjectName(_fromUtf8("viewLogTab"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.viewLogTab)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.logViewTab = QtGui.QTabWidget(self.viewLogTab)
        self.logViewTab.setMinimumSize(QtCore.QSize(380, 330))
        self.logViewTab.setToolTip(_fromUtf8(""))
        self.logViewTab.setTabPosition(QtGui.QTabWidget.North)
        self.logViewTab.setDocumentMode(False)
        self.logViewTab.setObjectName(_fromUtf8("logViewTab"))
        self.runViewTab = QtGui.QWidget()
        self.runViewTab.setObjectName(_fromUtf8("runViewTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.runViewTab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.runEntryViewTable = QtGui.QTableWidget(self.runViewTab)
        self.runEntryViewTable.setMinimumSize(QtCore.QSize(350, 300))
        self.runEntryViewTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.runEntryViewTable.setFont(font)
        self.runEntryViewTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.runEntryViewTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.runEntryViewTable.setObjectName(_fromUtf8("runEntryViewTable"))
        self.runEntryViewTable.setColumnCount(18)
        self.runEntryViewTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.runEntryViewTable.setHorizontalHeaderItem(17, item)
        self.gridLayout_2.addWidget(self.runEntryViewTable, 0, 0, 1, 1)
        self.logViewTab.addTab(self.runViewTab, _fromUtf8(""))
        self.TgcViewTab = QtGui.QWidget()
        self.TgcViewTab.setObjectName(_fromUtf8("TgcViewTab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.TgcViewTab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tgcEntryViewTable = QtGui.QTableWidget(self.TgcViewTab)
        self.tgcEntryViewTable.setMinimumSize(QtCore.QSize(350, 300))
        self.tgcEntryViewTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tgcEntryViewTable.setFont(font)
        self.tgcEntryViewTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.tgcEntryViewTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.tgcEntryViewTable.setObjectName(_fromUtf8("tgcEntryViewTable"))
        self.tgcEntryViewTable.setColumnCount(6)
        self.tgcEntryViewTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryViewTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryViewTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryViewTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryViewTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryViewTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tgcEntryViewTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_9.addWidget(self.tgcEntryViewTable)
        self.logViewTab.addTab(self.TgcViewTab, _fromUtf8(""))
        self.tbcViewTab = QtGui.QWidget()
        self.tbcViewTab.setObjectName(_fromUtf8("tbcViewTab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tbcViewTab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tbcEntryViewTable = QtGui.QTableWidget(self.tbcViewTab)
        self.tbcEntryViewTable.setMinimumSize(QtCore.QSize(350, 300))
        self.tbcEntryViewTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tbcEntryViewTable.setFont(font)
        self.tbcEntryViewTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.tbcEntryViewTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.tbcEntryViewTable.setObjectName(_fromUtf8("tbcEntryViewTable"))
        self.tbcEntryViewTable.setColumnCount(6)
        self.tbcEntryViewTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryViewTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryViewTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryViewTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryViewTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryViewTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tbcEntryViewTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_11.addWidget(self.tbcEntryViewTable)
        self.logViewTab.addTab(self.tbcViewTab, _fromUtf8(""))
        self.datViewTab = QtGui.QWidget()
        self.datViewTab.setObjectName(_fromUtf8("datViewTab"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.datViewTab)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.datEntryViewTable = QtGui.QTableWidget(self.datViewTab)
        self.datEntryViewTable.setMinimumSize(QtCore.QSize(350, 300))
        self.datEntryViewTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.datEntryViewTable.setFont(font)
        self.datEntryViewTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.datEntryViewTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.datEntryViewTable.setObjectName(_fromUtf8("datEntryViewTable"))
        self.datEntryViewTable.setColumnCount(5)
        self.datEntryViewTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryViewTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryViewTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryViewTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryViewTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.datEntryViewTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_12.addWidget(self.datEntryViewTable)
        self.logViewTab.addTab(self.datViewTab, _fromUtf8(""))
        self.bcViewTab = QtGui.QWidget()
        self.bcViewTab.setObjectName(_fromUtf8("bcViewTab"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.bcViewTab)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.bcEntryViewTable = QtGui.QTableWidget(self.bcViewTab)
        self.bcEntryViewTable.setMinimumSize(QtCore.QSize(350, 300))
        self.bcEntryViewTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bcEntryViewTable.setFont(font)
        self.bcEntryViewTable.setStyleSheet(_fromUtf8("font: 7pt \"MS Shell Dlg 2\";"))
        self.bcEntryViewTable.setFrameShape(QtGui.QFrame.WinPanel)
        self.bcEntryViewTable.setObjectName(_fromUtf8("bcEntryViewTable"))
        self.bcEntryViewTable.setColumnCount(5)
        self.bcEntryViewTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryViewTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryViewTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryViewTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryViewTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.bcEntryViewTable.setHorizontalHeaderItem(4, item)
        self.verticalLayout_13.addWidget(self.bcEntryViewTable)
        self.logViewTab.addTab(self.bcViewTab, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.logViewTab)
        self.tabWidget.addTab(self.viewLogTab, _fromUtf8(""))
        self.helpTab = QtGui.QWidget()
        self.helpTab.setObjectName(_fromUtf8("helpTab"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.helpTab)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.textEdit = QtGui.QTextEdit(self.helpTab)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_15.addWidget(self.textEdit)
        self.tabWidget.addTab(self.helpTab, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuExport = QtGui.QMenu(self.menuFile)
        self.menuExport.setToolTip(_fromUtf8(""))
        self.menuExport.setStatusTip(_fromUtf8(""))
        self.menuExport.setWhatsThis(_fromUtf8(""))
        self.menuExport.setObjectName(_fromUtf8("menuExport"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuTools = QtGui.QMenu(self.menuSettings)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.statusbar.setFont(font)
        self.statusbar.setAutoFillBackground(True)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExportToExcel = QtGui.QAction(MainWindow)
        self.actionExportToExcel.setObjectName(_fromUtf8("actionExportToExcel"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionNewModelLog = QtGui.QAction(MainWindow)
        self.actionNewModelLog.setObjectName(_fromUtf8("actionNewModelLog"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionUpdateDatabaseSchema = QtGui.QAction(MainWindow)
        self.actionUpdateDatabaseSchema.setObjectName(_fromUtf8("actionUpdateDatabaseSchema"))
        self.actionSaveSetupAs = QtGui.QAction(MainWindow)
        self.actionSaveSetupAs.setObjectName(_fromUtf8("actionSaveSetupAs"))
        self.actionLoadSetup = QtGui.QAction(MainWindow)
        self.actionLoadSetup.setObjectName(_fromUtf8("actionLoadSetup"))
        self.menuExport.addAction(self.actionExportToExcel)
        self.menuFile.addAction(self.actionNewModelLog)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionLoadSetup)
        self.menuFile.addAction(self.actionSaveSetupAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTools.addAction(self.actionUpdateDatabaseSchema)
        self.menuSettings.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.loadModelComboBox.setCurrentIndex(0)
        self.logViewTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LogIT", None))
        self.loadModelGroup.setTitle(_translate("MainWindow", "Load Model ", None))
        self.loadModelComboLabel.setText(_translate("MainWindow", "Model Type ", None))
        self.loadModelComboBox.setToolTip(_translate("MainWindow", "Type of model to log (default: Tuflow)", None))
        self.loadModelComboBox.setItemText(0, _translate("MainWindow", "TUFLOW (With ISIS/ESTRY If Found)", None))
        self.loadModelComboBox.setItemText(1, _translate("MainWindow", "ISIS Only", None))
        self.loadModelComboBox.setItemText(2, _translate("MainWindow", "ESTRY Only", None))
        self.loadModelButton.setToolTip(_translate("MainWindow", "Load an IEF or TCF file (Ctrl-L)", None))
        self.loadModelButton.setText(_translate("MainWindow", "Load Model...", None))
        self.inputVarGroup.setTitle(_translate("MainWindow", "Input Log Variables", None))
        self.modellerLabel.setText(_translate("MainWindow", "Modeller", None))
        self.eventNameLabel.setText(_translate("MainWindow", "Event Name", None))
        self.isisVersionLabel.setText(_translate("MainWindow", "Isis Version", None))
        self.tuflowVersionLabel.setText(_translate("MainWindow", "Tuflow Version", None))
        self.RunGroup.setTitle(_translate("MainWindow", "Run Variables", None))
        self.runEntryTable.setSortingEnabled(False)
        item = self.runEntryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vars", None))
        item = self.runEntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.runEntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MODELLER", None))
        item = self.runEntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "RESULTS_LOCATION_2D", None))
        item = self.runEntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RESULTS_LOCATION_1D", None))
        item = self.runEntryTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "EVENT_DURATION", None))
        item = self.runEntryTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "DESCRIPTION", None))
        item = self.runEntryTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        item = self.runEntryTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "SETUP", None))
        item = self.runEntryTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ISIS_BUILD", None))
        item = self.runEntryTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "IEF", None))
        item = self.runEntryTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "DAT", None))
        item = self.runEntryTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "TUFLOW_BUILD", None))
        item = self.runEntryTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "TCF", None))
        item = self.runEntryTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "TGC", None))
        item = self.runEntryTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "TBC", None))
        item = self.runEntryTable.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "BC_DBASE", None))
        item = self.runEntryTable.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "EVENT_NAME", None))
        __sortingEnabled = self.runEntryTable.isSortingEnabled()
        self.runEntryTable.setSortingEnabled(False)
        self.runEntryTable.setSortingEnabled(__sortingEnabled)
        self.tgcGroup.setTitle(_translate("MainWindow", "Tgc Variables", None))
        item = self.tgcEntryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vars", None))
        item = self.tgcEntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.tgcEntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TGC", None))
        item = self.tgcEntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FILES", None))
        item = self.tgcEntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        __sortingEnabled = self.tgcEntryTable.isSortingEnabled()
        self.tgcEntryTable.setSortingEnabled(False)
        self.tgcEntryTable.setSortingEnabled(__sortingEnabled)
        self.tbcGroup.setTitle(_translate("MainWindow", "Tbc Variables", None))
        item = self.tbcEntryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vars", None))
        item = self.tbcEntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.tbcEntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TBC", None))
        item = self.tbcEntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "FILES", None))
        item = self.tbcEntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        __sortingEnabled = self.tbcEntryTable.isSortingEnabled()
        self.tbcEntryTable.setSortingEnabled(False)
        self.tbcEntryTable.setSortingEnabled(__sortingEnabled)
        self.datGroup.setTitle(_translate("MainWindow", "Dat Variables", None))
        item = self.datEntryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vars", None))
        item = self.datEntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.datEntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DAT", None))
        item = self.datEntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "AMENDMENTS", None))
        item = self.datEntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        __sortingEnabled = self.datEntryTable.isSortingEnabled()
        self.datEntryTable.setSortingEnabled(False)
        self.datEntryTable.setSortingEnabled(__sortingEnabled)
        self.bcGroup.setTitle(_translate("MainWindow", "BC DBase Variables", None))
        item = self.bcEntryTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Vars", None))
        item = self.bcEntryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.bcEntryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "BC_DBASE", None))
        item = self.bcEntryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "AMENDMENTS", None))
        item = self.bcEntryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        __sortingEnabled = self.bcEntryTable.isSortingEnabled()
        self.bcEntryTable.setSortingEnabled(False)
        self.bcEntryTable.setSortingEnabled(__sortingEnabled)
        self.addlogEntryButton.setToolTip(_translate("MainWindow", "Add loaded model data to database (Ctrl-A)", None))
        self.addlogEntryButton.setText(_translate("MainWindow", "Add New Log Entry", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.newEntryTab), _translate("MainWindow", "New Log Entry", None))
        self.runEntryViewTable.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Right-click row entry to delete or update</span></p></body></html>", None))
        self.runEntryViewTable.setAccessibleName(_translate("MainWindow", "runViewEntryTable", None))
        self.runEntryViewTable.setSortingEnabled(True)
        item = self.runEntryViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.runEntryViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.runEntryViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MODELLER", None))
        item = self.runEntryViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RESULTS_LOCATION_2D", None))
        item = self.runEntryViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "RESULTS_LOCATION_1D", None))
        item = self.runEntryViewTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "EVENT_DURATION", None))
        item = self.runEntryViewTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "DESCRIPTION", None))
        item = self.runEntryViewTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        item = self.runEntryViewTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "SETUP", None))
        item = self.runEntryViewTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "ISIS_BUILD", None))
        item = self.runEntryViewTable.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "IEF", None))
        item = self.runEntryViewTable.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "DAT", None))
        item = self.runEntryViewTable.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "TUFLOW_BUILD", None))
        item = self.runEntryViewTable.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "TCF", None))
        item = self.runEntryViewTable.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "TGC", None))
        item = self.runEntryViewTable.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "TBC", None))
        item = self.runEntryViewTable.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "BC_DBASE", None))
        item = self.runEntryViewTable.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "EVENT_NAME", None))
        self.logViewTab.setTabText(self.logViewTab.indexOf(self.runViewTab), _translate("MainWindow", " Run Log", None))
        self.tgcEntryViewTable.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Right-click row entry to delete or update</span></p></body></html>", None))
        self.tgcEntryViewTable.setSortingEnabled(True)
        item = self.tgcEntryViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.tgcEntryViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.tgcEntryViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TGC", None))
        item = self.tgcEntryViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FILES", None))
        item = self.tgcEntryViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NEW_FILES", None))
        item = self.tgcEntryViewTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        self.logViewTab.setTabText(self.logViewTab.indexOf(self.TgcViewTab), _translate("MainWindow", "Tgc Log", None))
        self.tbcEntryViewTable.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Right-click row entry to delete or update</span></p></body></html>", None))
        self.tbcEntryViewTable.setSortingEnabled(True)
        item = self.tbcEntryViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.tbcEntryViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.tbcEntryViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TBC", None))
        item = self.tbcEntryViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FILES", None))
        item = self.tbcEntryViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "NEW_FILES", None))
        item = self.tbcEntryViewTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        self.logViewTab.setTabText(self.logViewTab.indexOf(self.tbcViewTab), _translate("MainWindow", "Tbc Log", None))
        self.datEntryViewTable.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Right-click row entry to delete or update</span></p></body></html>", None))
        self.datEntryViewTable.setSortingEnabled(True)
        item = self.datEntryViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.datEntryViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.datEntryViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DAT", None))
        item = self.datEntryViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AMENDMENTS", None))
        item = self.datEntryViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        self.logViewTab.setTabText(self.logViewTab.indexOf(self.datViewTab), _translate("MainWindow", "Dat Log", None))
        self.bcEntryViewTable.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Right-click row entry to delete or update</span></p></body></html>", None))
        self.bcEntryViewTable.setSortingEnabled(True)
        item = self.bcEntryViewTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.bcEntryViewTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "DATE", None))
        item = self.bcEntryViewTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "BC_DBASE", None))
        item = self.bcEntryViewTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AMENDMENTS", None))
        item = self.bcEntryViewTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "COMMENTS", None))
        self.logViewTab.setTabText(self.logViewTab.indexOf(self.bcViewTab), _translate("MainWindow", "BC Log", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewLogTab), _translate("MainWindow", "View Log", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">LogIT v0.1</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; text-decoration: underline;\">Info</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Name: LogIT (Logger for Isis and Tuflow) </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Version: 0.1-Beta</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Author: Duncan Runnacles</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Copyright: (C) 2014 Duncan Runnacles</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">email: duncan.runnacles@thomasmackay.co.uk</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">License: GPL v2 - Available at: http://www.gnu.org/licenses/gpl-2.0.html</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the license, or (at your option) any later version.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRENTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; text-decoration: underline;\">Summary</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">LogIT provides an interface for logging run specific information from ISIS and TUFLOW models. It supports loading of ISIS Event Files (*.ief) and TUFLOW run files (*.tcf). There is currently no support for ESTRY run files (*.ecf), although there are plans to implement this.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Once a model has been loaded it will read key model information into tables that can be amended and added to the database. The database can be exported to Excel format at any time.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; text-decoration: underline;\">Instructions</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Create a database:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Before a model log can be loaded you need to create a log database. This can be done through the File &gt; Create New Model Log menu (Ctrl+N).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">A different database can be loaded at any time using the File &gt; Load Model Log menu (Ctrl-O).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">LogIT will attempt to load the last used database when you open the software.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Load Model:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Prior to loading the model you can enter the Input Log Variables. These will then be included in the Variable tables once the model is loaded. They will also be remembered when LogIT is restarted.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">To load a model for logging click the Load Model button (Ctrl-L).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The key variables from the model will be entered into the Variables tables on the New Log Entry tab. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Some of the cells in the table are editable prior to adding to the database. These cells will be coloured green. If certain files already exist in the database they cannot be re-entered, so any changes to comment cells etc will not be stored, these rows will be coloured red.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Add Log Entry:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">When you have finished editing the log entry you can enter it in the database by clicking the Add New Log Entry button (Ctrl-A).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This will store the log entry exactly as shown in the Variables tables into the log database and show the updated log in the View Log tab tables.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Editing Existing Log Entries:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">It is possible to edit log entries that have already been added to the log database in the View Log tab. However only certain cells are editable.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">To edit a cell: double click the required cell and edit the entry. Once you have completed all required edits for that row you can update the database by right clicking anywhere in the row and selecting Update Row. Changes to the database can only be done on a row-by-row basis.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Delete Log Entry:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Deleting entries from the log database can be done in the View Log tab tables. It is not possible to remove an entire entry at once because multiple run log entries may refer to a single tgc/tbc/dat/bc dbase entry. Thus entries in the different tables must be deleted seperately.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">To delete an entry right click the row to delete from the table and select Delete Row.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Exporting to Excel:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Exporting the log databse to Excel format can be done through the File &gt; Export &gt; Excel Menu (Ctrl+E).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This will export all of the existing database tables to an Excel Workbook. A Worksheet will be created for each of the exported database tables.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">There is an Excel VBA Module called LogFormatter.bas available in the distribution folder for &quot;pretifying&quot; the exported Workbook. To use it:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">1) Open the exported Excel Workbook.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">2) Open the Visual Basic window.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">3) Right-Click on your log book project.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">4) Click &quot;Import File...&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">5) Find the LogFormatter.bas file in the LogIT folder and open it.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">6) Go back to the Excel Workbook and under developer click &quot;Macros&quot;).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">7) Depending on whether you have any other Workbooks open or not the Macro </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   will either be caller &quot;formatLogbook&quot; or &quot;LogFormatter.formatLogbook&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">   Select it and click &quot;Run&quot;.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">The jumbled output from the software should now be nicely formatted :)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Update Database Schema:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">When a new version of LogIT is released there may be changes to the way that the log database is setup. If this happens the database must be updated in order to use the new version. Settings &gt; Tools &gt; Update Database Schema will make a backup of the existing database and attempt to update it.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Load/Save Setup:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">When you start LogIT it will attempt to load the settings that you last used from a local file. These include Input variables, log database, etc.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">If you have particular setups for certain logs, such as different Isis or Tuflow versions, you can save a settings file and load it at any time using File &gt; Load Setup and File &gt; Save Setup As...</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; text-decoration: underline;\">Current Limitations</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">LogIT does not currently know how to read Estry Control Files (*.ecf). Any files that are referenced through an ecf will not be found. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Although there are tables for Boundary Condition Database\'s (BC_DBASE) there is not currently any implementation for these files. This is due to the lack of .ecf file support.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">These capabilities will be implemented once they are supported by the tmac_tools_lib package used to load the models into LogIT.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; text-decoration: underline;\">Common Errors</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Some common errors can occur when loading files. These are outlined here.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Load Error - Unable to load model from file at: filename:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">This can be caused by several issues that may be bugs. A common cause is trying to load a model from an IEF file which has unfindable paths. Check the log for the error; if it says &quot;Tcf file referenced by ief does not exist at: filename&quot; make sure that filename exists and is findable. This error can also be caused by having the Model Type combo box set incorrectly for the type of model you are trying to load - check the error log for further details.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600; text-decoration: underline;\">Reporting Bugs</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600; text-decoration: underline;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">If you find an error that is not included in the Common Errors list above please report it as a bug to duncan.runnacles@thomasmackay.co.uk.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">There should be a folder called /logs/ in the same folder as the executable. This should be zipped up and sent along with any bug report. If this folder is empty there has been a problem wth setting up the logging on your computer (probably due to access rights or a virus checker not allowing LogIT to write to disc - If this is the case a warning will be sent to the console saying &quot;Unable to create log file directory&quot;). To get the log entry you can try and reproduce the error and copy the text from the console window. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Any other details about the contents and setup of the model that you are trying to log should also be included in the bug report. It may be easier to just send the ief/tcf/tgc/tbc/trd files if you are happy to do it. </span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.helpTab), _translate("MainWindow", "Help", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuExport.setTitle(_translate("MainWindow", "Export", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.actionExportToExcel.setText(_translate("MainWindow", "Excel", None))
        self.actionExportToExcel.setToolTip(_translate("MainWindow", "Export model log database to Excel (*.xls) Workbook", None))
        self.actionExportToExcel.setStatusTip(_translate("MainWindow", "Export model log database to Excel (*.xls) Workbook", None))
        self.actionExportToExcel.setWhatsThis(_translate("MainWindow", "Export model log database to Excel (*.xls) Workbook", None))
        self.actionLoad.setText(_translate("MainWindow", "Load Model Log", None))
        self.actionLoad.setToolTip(_translate("MainWindow", "Load existing model log from file", None))
        self.actionLoad.setStatusTip(_translate("MainWindow", "Load existing model log from file", None))
        self.actionLoad.setWhatsThis(_translate("MainWindow", "Load existing model log from file", None))
        self.actionNewModelLog.setText(_translate("MainWindow", "Create New Model Log", None))
        self.actionNewModelLog.setToolTip(_translate("MainWindow", "Create new model log database", None))
        self.actionNewModelLog.setStatusTip(_translate("MainWindow", "Create new model log database", None))
        self.actionNewModelLog.setWhatsThis(_translate("MainWindow", "Create new model log database", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Quit LogIT", None))
        self.actionExit.setStatusTip(_translate("MainWindow", "Quit LogIT", None))
        self.actionExit.setWhatsThis(_translate("MainWindow", "Quit LogIT", None))
        self.actionUpdateDatabaseSchema.setText(_translate("MainWindow", "Update Database Schema", None))
        self.actionUpdateDatabaseSchema.setToolTip(_translate("MainWindow", "Update an existing database to the format used with the latest version of LogIT", None))
        self.actionUpdateDatabaseSchema.setStatusTip(_translate("MainWindow", "Update an existing database to the format used with the latest version of LogIT", None))
        self.actionUpdateDatabaseSchema.setWhatsThis(_translate("MainWindow", "Update an existing database to the format used with the latest version of LogIT", None))
        self.actionSaveSetupAs.setText(_translate("MainWindow", "Save Setup As...", None))
        self.actionSaveSetupAs.setToolTip(_translate("MainWindow", "Save current setup of LogIT (Input Variables, connected database, etc) to file.", None))
        self.actionSaveSetupAs.setStatusTip(_translate("MainWindow", "Save current setup of LogIT (Input Variables, connected database, etc) to file.", None))
        self.actionSaveSetupAs.setWhatsThis(_translate("MainWindow", "Save current setup of LogIT (Input Variables, connected database, etc) to file.", None))
        self.actionLoadSetup.setText(_translate("MainWindow", "Load Setup", None))
        self.actionLoadSetup.setToolTip(_translate("MainWindow", "Load setup of LogIT (Input Variables, connected database, etc) from file.", None))
        self.actionLoadSetup.setStatusTip(_translate("MainWindow", "Load setup of LogIT (Input Variables, connected database, etc) from file.", None))
        self.actionLoadSetup.setWhatsThis(_translate("MainWindow", "Load setup of LogIT (Input Variables, connected database, etc) from file.", None))

